kosli-dev/cli

- cmd/kosli/expectDeployment.go
- cmd/kosli/expectDeployment_test.go
- docs.kosli.com/content/getting_started/deployments.md
Relates to https://github.com/kosli-dev/server/issues/811
> Update documentation to reflect deployment expectations usage

- cmd/kosli/reportApproval.go
- cmd/kosli/root.go
> add --approver flag to report approval

- .github/workflows/publish_branch_docs.yml
- Add workflow for branch deployment of docs
- edit docs branch deploy workflow
> docs branch deploy workflow

- cmd/kosli/assertPRAzure.go
- cmd/kosli/assertPRBitbucket.go
- cmd/kosli/assertPRGithub.go
- cmd/kosli/assertPRGitlab.go
- cmd/kosli/attestJira.go
- cmd/kosli/pullrequest.go
- cmd/kosli/reportEvidenceCommitJira.go
> report evidence/attestation before failing when --assert is used

- cmd/kosli/pullrequest.go
- cmd/kosli/reportEvidenceArtifactPRAzure_test.go
- cmd/kosli/reportEvidenceArtifactPRBitbucket_test.go
- cmd/kosli/reportEvidenceArtifactPRGithub_test.go
- cmd/kosli/reportEvidenceArtifactPRGitlab_test.go
> only fail pr asserts when no PRs found

- cmd/kosli/fingerprint.go
- cmd/kosli/reportEvidenceArtifactSnyk.go
- cmd/kosli/reportEvidenceCommitSnyk.go
- cmd/kosli/root.go
- cmd/kosli/snapshotAzureApps_test.go
- cmd/kosli/testdata/output/docs/artifact.md
- internal/snyk/snyk.go
this fixes some bugs when some snyk values are empty.
> check for nil values in snyk results and update cli docs

- cmd/kosli/createEnvironment.go
- cmd/kosli/createEnvironment_test.go
- cmd/kosli/root.go
- Environment: Added option to spesify if an environment should include or exclude scaling
- Removed commented out code
> Implemented support to enable or disable scaling for an environment

- .github/workflows/helm-chart.yml
Fixes bug reported https://github.com/peter-evans/create-pull-request/issues/2790
> Update helm-chart.yml workflow

- cmd/kosli/root.go
this PR fixes 2 issues:
- api token set via env variable was treated the same as the one coming from env variable (CLI attempts to decrypt it when it is not encrypted).
- errors during api token decryption were not emitted
> fix trying to decrypt api token when it is set via env var

- cmd/kosli/testdata/output/docs/snyk.md
- Put live examples for gitlab and github in tabs
- Update test data for docs
> live docs tabs

- cmd/kosli/config.go
> unhide config command

- docs.kosli.com/content/tutorials/cli_and_http_proxy.md
related to kosli-dev/server#1749
> add a tutorial for using CLI with an http proxy

- cmd/kosli/cli_utils.go
> support aws code build default values

- internal/requests/requests.go
- internal/requests/requests_test.go
> don't send empty body in GET requests

- cmd/kosli/getFlow.go
> fix new flow template rendering

- charts/k8s-reporter/_templates.gotmpl
> mention the minimum supported k8s version

- cmd/kosli/reportEvidenceArtifactSnyk.go
- internal/snyk/snyk.go
- internal/snyk/snyk_test.go
consider note level vulnerabilities as low vulnerabilities in snyk sarif results
> consider note level vulnerabilities in snyk sarif results

- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- cmd/kosli/snapshotAzureApps_test.go
- **Pass Azure Client Secret and ID into tests**
- **Introduce new secrets**
> shared azure service principal

- cmd/kosli/cli_utils.go
- cmd/kosli/cli_utils_test.go
- cmd/kosli/get.go
- cmd/kosli/getTrail.go
- cmd/kosli/getTrail_test.go
- cmd/kosli/list.go
- cmd/kosli/listTrails.go
- cmd/kosli/listTrails_test.go
- cmd/kosli/testdata/output/get/get-trail.txt
> Trails read cmds

- cmd/kosli/attestArtifact.go
- cmd/kosli/attestArtifact_test.go
- cmd/kosli/attestGeneric.go
- cmd/kosli/attestJira.go
- cmd/kosli/attestJunit.go
- cmd/kosli/attestPRAzure.go
- cmd/kosli/attestPRBitbucket.go
- cmd/kosli/attestPRGithub.go
- cmd/kosli/attestPRGitlab.go
- cmd/kosli/attestSnyk.go
- cmd/kosli/attestation.go
- cmd/kosli/beginTrail.go
- cmd/kosli/beginTrail_test.go
- cmd/kosli/cli_utils.go
- cmd/kosli/cli_utils_test.go
- cmd/kosli/flags.go
- cmd/kosli/reportArtifact.go
- cmd/kosli/root.go
- cmd/kosli/testdata/output/docs/snyk.md
- internal/gitview/gitView.go
- internal/gitview/gitView_test.go
> allow redacting some commit info

- cmd/kosli/attachPolicy.go
- cmd/kosli/create.go
- cmd/kosli/createPolicy.go
- cmd/kosli/detachPolicy.go
- cmd/kosli/root.go
relates to kosli-dev/server#1943
> add hidden policy cmds

- cmd/kosli/fingerprint.go
- cmd/kosli/root.go
> update fingerprint docs

- bin/never_alone_create_pull_request_for_old_commit.sh
- bin/never_alone_get_commits_with_pull_request_info.sh
- bin/never_alone_get_failing_pull_requests.sh
- **Never alone: Added info if commiter and approver is the same person**
- **Never alone: added script to add pull request for all commit**
- **Removed commented out code**
> Never alone, small update to include reason if committer and approver is the same person"

- .github/workflows/init_kosli.yml
- bin/never_alone_create_review_trail.sh
- bin/never_alone_report_commit_and_pr_to_kosli.sh
- **Added reporting to new flow cli-release-code-reviews**
- **Added review trail as a generic evidence in the flow that builds**
> Report commits and pull-reqeust in seperate flow. Link the flow in the cli/cli-release flow

- bin/never_alone_create_review_trail.sh
- bin/never_alone_report_commit_and_pr_to_kosli.sh
- **Find last approved reviewer and not lastReviews**
- **Look at all approvals and find at least one where the approver is not the commiter**
> Look at all approvals and find at least one where the approver is not the commiter

- .github/workflows/init_kosli.yml
- bin/never_alone_report_commit_and_pr_to_kosli.sh
- **Added the commit sha to the kosli attest command**
- **Never alone: attest the code-review with correct compliance**
> never alone 6

- cmd/kosli/attestGeneric.go
- cmd/kosli/attestJira.go
- cmd/kosli/attestJunit.go
- cmd/kosli/attestSnyk.go
- cmd/kosli/attestation.go
- cmd/kosli/cli_utils.go
- cmd/kosli/testdata/output/docs/snyk.md
- internal/requests/requests.go
- internal/sonar/sonar.go
See https://github.com/kosli-dev/cli/issues/295
> Fix minor error in some docs examples

- charts/k8s-reporter/README.md
- docs.kosli.com/content/helm/_index.md
> Update helm docs

- .github/workflows/init_kosli.yml
- .github/workflows/never_alone_trail.yml
- bin/never_alone/create_never_alone_trail.sh
- **Some cleanup**
- **Added reason for non compliance**
> never alone cleanup 1

- .github/workflows/main.yml
- .github/workflows/release.yml
- bin/never_alone/create_never_alone_trail.sh
- **Started on getting ux url**
- **Get attestation url from server**
- **Report over all compliance of never-alone trail when attesting never-alone-trail to release trail**
- **Require that init-kosli has ran before starting tests**
- **Require that init-kosli has ran before starting tests, for relase build**
> Make link to attestation a proper link. Require init-kosli before running tests in CI

- cmd/kosli/add.go
- cmd/kosli/addEnvironment.go
- cmd/kosli/addEnvironment_test.go
- cmd/kosli/root.go
- **Started on kosli add environment**
- **Added tests for add environment command**
> add physical to logical

- Makefile
- cmd/kosli/createEnvironment_test.go
- cmd/kosli/createFlow_test.go
- cmd/kosli/renameEnvironment_test.go
- cmd/kosli/renameFlow_test.go
- **Fixed some tests, updated Makefile**
- **Fixed rename env tests**
> fix test after server upgrade

- docs.kosli.com/content/template_ref/_index.md
related to kosli-dev/server#2602
> replace any with *

- cmd/kosli/beginTrail_test.go
- cmd/kosli/createFlow_test.go
We've changed the output that we get from the server.
I think we probably need to provide some better messaging from the
server than what we get now, perhaps we should look at catching thise
errors, and reporting better.
> Fix failing test

- cmd/kosli/attestGeneric.go
- cmd/kosli/create.go
- cmd/kosli/createAttestationType.go
- cmd/kosli/createAttestationType_test.go
- cmd/kosli/root.go
- cmd/kosli/testdata/person-schema.json
- **Walking skeleton**
- **Add test for successfully creating a new custom attestation type**
- **Add description flag to custom attestation creation command**
- **Send the schema**
- **Send JQ evaluators**
- **Send JQ evaluator rules**
- **Add docs**
- **Hide commnad**
> create attestation type command

- cmd/kosli/doubledHost.go
- cmd/kosli/main.go
- cmd/kosli/root.go
- cmd/kosli/testHelpers.go
- internal/logger/logger.go
> log debug info to stderr

- docs.kosli.com/content/getting_started/attestations.md
See also 
- https://github.com/kosli-dev/cli/issues/415
- https://github.com/kosli-dev/cli/issues/416
> Minor doc text tweaks while doing general run through after hugo update

- cmd/kosli/archiveAttestationType.go
- cmd/kosli/attestCustom.go
- cmd/kosli/createAttestationType.go
> Display documentation for custom attestation commands

- cmd/kosli/attestJira_test.go
- internal/jira/jira.go
Struggled to recreate this in tests, but saw it on the CLI
> Prevent nil reference error
