kosli-dev/cli

internal/aws/aws.go
while testing lambda reporting I realised sha was incorrect. It turns out amazon used base64 for sha
I fixed it and can confirm we're getting good sha now, but maybe there is a nicer way
=> CodeSha256: base64 to hex

cmd/kosli/reportEvidenceCommitJira.go, cmd/kosli/reportEvidenceCommitJira_test.go, cmd/kosli/root.go, internal/gitview/gitView.go, internal/gitview/gitView_test.go, internal/testHelpers/testHelpers.go
- Add a failing test for pulling jira reference from branch
- Add a test for checking branch name with Jira
- Added `--assert` option to `report evidence commit jira`
related to kosli-dev/server#1018
=> Add `--assert` option for reporting jira evidence

.github/workflows/auto-approve.yml
- CI: use fine-grained API token instead of default GH token in auto-approve ci
- Add more logging to auto-approve ci for debugging
=> 1021 auto merge ci

cmd/kosli/cli_utils.go
=> copy with full path instead of just base name of file or dir

.github/workflows/auto-approve.yml, .github/workflows/helm-chart.yml
when helm chart is updated, CI attempts to push the updated docs back to main to release them later in the release workflow.
Currently, this [fails due to branch protection](https://github.com/kosli-dev/cli/actions/runs/7530331081/job/20496459283). This PR switches to creating a PR and auto-merge it instead of a direct push.
=> fix pushing helm docs back to main

cmd/kosli/snapshotECS_test.go, docs.kosli.com/static/_redirects
=> add a netlify redirect for old what is kosli page

.github/workflows/docker.yml, .github/workflows/release.yml, .snyk, cmd/kosli/attestArtifact.go, cmd/kosli/attestation.go, cmd/kosli/beginTrail.go, cmd/kosli/cli_utils.go, cmd/kosli/reportArtifact.go, internal/gitview/gitView.go, internal/gitview/gitView_test.go
- add snyk policy
- assert cli before releasing it
- attempt to capture commit url in commit_info and send it for artifact reports and attestations.
=> Report commit url for artifacts and attestations

cmd/kosli/cli_utils.go
- Added debug info to test out on windows
- Changed to path without colon
- Removed some debug info
=> Fixed bug with Windows absolute path in evidence-paths. Do not include colon in the destination tar ball kosli-dev/server#1521

.github/workflows/docker.yml, .github/workflows/main.yml, .github/workflows/release.yml, charts/k8s-reporter/Chart.yaml, docs.kosli.com/content/helm/_index.md
- Helm: Updated platforms to include both amd64 and arm64
- Build for helm chart arm64 only on release
- Updated typo in docs
- Helm: Updated kosli version to 2.8.5
=> Updated docker image for release to be multi arch with amd64 and arm64

charts/k8s-reporter/Chart.yaml, charts/k8s-reporter/values.yaml
This will use the multi-architecture build to enable kosli reporter on AWS Graviton 🤞
=> Update helm chart to v2.8.6

cmd/kosli/attestArtifact.go, cmd/kosli/getEnvironment.go, cmd/kosli/getFlow.go, cmd/kosli/getSnapshot.go, cmd/kosli/listEnvironments.go, cmd/kosli/listFlows.go, cmd/kosli/root.go, cmd/kosli/status_test.go, cmd/kosli/tag.go, cmd/kosli/tag_test.go
related to kosli-dev/server#1587
- add hidden command to tag flows and environments
- include tags in the tabular output of list flows, get flow, list envs, get env commands
-  include compliance in get snapshot tabular output
=> add hidden tag command

Makefile, cmd/kosli/config.go, cmd/kosli/config_test.go, cmd/kosli/doubledHost_test.go, cmd/kosli/root.go, cmd/kosli/tag.go, go.mod, go.sum, internal/security/security.go, internal/security/security_test.go
this is for kosli-dev/server#1653
- make the tag command public
- remove long deprecated verbose flag
- add a hidden config command
e.g `kosli config --api-token xxxx` => creates ~/.kosli.yml with encrypted token using a key from the local credentials store on the machine
=> Config command

cmd/kosli/tag.go
Tag names appear to printed in a non-deterministic order.
For example see
https://github.com/kosli-dev/cli/actions/runs/8480970891/job/23237582028#step:8:313
=> Sort tag names so output is deterministic (eg for tests)

cmd/kosli/config.go, cmd/kosli/main.go, cmd/kosli/root.go, internal/digest/digest.go, internal/requests/requests.go, internal/requests/requests_test.go
fixes kosli-dev/server#1749 
- Kosli client can be created with an http proxy
- http proxy can be set via global flag, env var or in the kosli config file
=> support making requests via an http proxy

.github/workflows/helm-chart.yml
GPG signature is pulled in CI and used to sign commits made for the PR that CI creates to update the helm docs on the live docs.
=> ensure git commits made in helm docs updating PRs are signed

cmd/kosli/root.go, cmd/kosli/snapshot.go, cmd/kosli/snapshotPath.go, cmd/kosli/snapshotPath_test.go, cmd/kosli/snapshotPaths.go, cmd/kosli/snapshotPaths_test.go
split `kosli snapshot paths` to 2 commands as suggested in [this comment](https://github.com/kosli-dev/server/issues/1714#issuecomment-2082144893):
- `kosli snapshot paths  <env-name> --paths-file ...` for one or multiple artifacts reporting using a paths file
- `kosli snapshot path  <env-name> --path ./path --name foo --exclude *.logs` for single artifact reporting without paths file
=> Split snapshot paths

cmd/kosli/createEnvironment.go, cmd/kosli/createEnvironment_test.go, cmd/kosli/getEnvironment.go, cmd/kosli/root.go
partially fulfils kosli-dev/server#1705.
- adds `--require-provenance` flag on `kosli create env`
- shows `require provenace` settings value in `kosli get env`
=> 1705 allow no provenance envs

.github/workflows/docker.yml, .github/workflows/main.yml, .github/workflows/test.yml, .gitignore, Makefile, main-flow-template.yml, release-flow-template.yml
related to kosli-dev/server#1867
- parallelize CI tasks where possible
- use Github attestations for the docker image artifact
- generate SBOM for the docker image artifact
- start tracking CLI in a new Flow with trails
- record builds on main
results look like: https://app.kosli.com/kosli-public/flows/cli/trails/feb74ee
=> Use trails for the CLI artifact

.github/workflows/test.yml
We are getting errors during linting. This newer version handles package cache differently, fixing these:
=> Update golint action version

cmd/kosli/attestGeneric.go, cmd/kosli/attestJira.go, cmd/kosli/attestJunit.go, cmd/kosli/attestPRAzure.go, cmd/kosli/attestPRBitbucket.go, cmd/kosli/attestPRGithub.go, cmd/kosli/attestPRGitlab.go, cmd/kosli/attestSnyk.go, cmd/kosli/attestation.go, cmd/kosli/begin.go, cmd/kosli/pullrequest.go, cmd/kosli/root.go, cmd/kosli/testdata/output/docs/snyk.md
- convert raw API error for attestations targeting artifacts by name only. relates to kosli-dev/server#1888
- improve attestation docs #203
=> improve docs/help and error messages

docs.kosli.com/content/tutorials/attest_snyk.md, docs.kosli.com/content/tutorials/cli_and_http_proxy.md, docs.kosli.com/content/tutorials/querying_kosli.md, docs.kosli.com/content/tutorials/report_aws_envs.md, docs.kosli.com/content/tutorials/report_k8s_envs.md, docs.kosli.com/content/tutorials/unauthorized_iac_changes.md
In the Swiss Digital Network training there were several times when Olivier (for example) copied a fragment from the tutorials, pasted it into a text editor, and then had to delete the leading dollar symbols.
=> Remove leading dollar from all bash fragments

internal/gitview/gitView.go, internal/gitview/gitView_test.go
default commit url when git providers are self-hosted and have custom domains.
Caveat: this won't work for self-hosted Bitbucket (Bitbucket Data Center)
=> default commit url when git providers are self-hosted

cmd/kosli/attestGeneric_test.go, cmd/kosli/cli_utils.go
I've updated the statement in ValidateAttestationArtifactArg to include a check for fingerprint==""
I wonder if this statement would be better in the ValidateArtifactArg function at line 507 ?
https://github.com/kosli-dev/cli/pull/280/files#diff-367af2489094e782fd18bfef89eb313d9f396f8aac2891268e47a1cb48546f9aL507
=> Fix erroneous attest error

.github/workflows/main.yml, .github/workflows/never_alone_trail.yml, .github/workflows/release.yml, bin/never_alone/create_never_alone_trail.sh, bin/never_alone/get_commit_and_pr_info.sh
- **Took out docker part of build to speed up**
- **Started on adding a never-alone-trail attestation to the cli-release**
- **Added setup of kosli cli before report of never-alone-trail**
- **fixed extra argument to kosli attest**
- **Fixed trailing white space**
- **Added git repo of depth 1**
- **Updated to a new release number**
- **Moved attestation of never-alone-trail into bash script**
- **Added begin trail for the test parent flow**
- **Added -p and -q options when calling create_never_alone_trail**
- **Some cleanup**
=> Added reporting an attestation to the relase pointing back to the never-alone-trail #2298

cmd/kosli/root.go, cmd/kosli/snapshotLambda.go, cmd/kosli/snapshotLambda_test.go, internal/aws/aws.go, internal/aws/aws_test.go
related to kosli-dev/server#2222
=> add --exclude and --exclude-regex flags to snapshot lambda command

cmd/kosli/assertArtifact_test.go
This test seems to get different responses from the server - sometimes
there is a `?artifact_id=...` appended, sometimes there isn't.
I guess this is related to the flow v1->v2 migration? So this makes the
artifact_id optional, for now.
=> Use optional regex group

.github/workflows/main.yml, .github/workflows/release.yml, .github/workflows/test.yml, cmd/kosli/assertPRBitbucket_test.go, cmd/kosli/attestPRBitbucket_test.go, cmd/kosli/cli_utils_test.go, cmd/kosli/reportEvidenceArtifactPRBitbucket_test.go, cmd/kosli/reportEvidenceCommitPRBitbucket_test.go, internal/gitview/gitView_test.go, secrets/gh-repo-kosli-bitbucket-password.txt, secrets/gh-repo-kosli-bitbucket-username.txt, secrets/gh-repo-kosli-gitlab-token.txt
- **Works with kosli-dev and user tore1**
- **Moved bitbucket username out as a secret since it has to match the password for that user**
- **Removed ewelinz**
- **Added bitbucket username to github workflows**
- **Added missing bitbucket username**
=> Changed bitbucket tests to use kosli-dev and not ewelina kosli-dev/server#2461

docs.kosli.com/content/getting_started/environments.md, docs.kosli.com/content/tutorials/report_aws_envs.md
related to kosli-dev/server#2397
=> add environment snapshotting scopes table

.github/workflows/test.yml, bin/reset-or-start-server.sh, docker-compose.yml
- **Updated server-index with hostname and test-mode so it picks correct documentDB password**
- **Disable snyk-code since out of free tests this month**
=> Updated server-index with hostname and test-mode so it picks correct documentDB password

cmd/kosli/attestJira.go, cmd/kosli/attestJira_test.go, cmd/kosli/reportEvidenceCommitJira.go, cmd/kosli/root.go, internal/jira/jira.go
- **Added jira-issue-fields to attest jira command**
- **Removed comment about Creator**
- **Added test of jira fields**
=> Added support for jira issue fields

cmd/kosli/assertArtifact.go, cmd/kosli/assertArtifact_test.go, cmd/kosli/root.go
related to kosli-dev/server#1943
=> allow asserting an artifact for an environment

internal/requests/requests.go
with v2.6.11, adding `--debug` causes duplicate logging with inconsistent formatting:
```
$ kosli list flows --debug 
[debug] processing config file [/Users/samialajrami/.kosli.yml]
[debug] using api token from [/Users/samialajrami/.kosli.yml].
2025/02/18 10:59:14 [DEBUG] GET https://app.kosli.com/api/v2/flows/kosli <==== this is duplicate and has a different format
[debug] request made to https://app.kosli.com/api/v2/flows/kosli and got status 200
```
without the duplicate logging, this is what it looks on a retry call:
```
$ kosli list flows --debug 
[debug] processing config file [/Users/samialajrami/.kosli.yml]
[debug] using api token from [/Users/samialajrami/.kosli.yml].
Error: Get "http://localhost/api/v2/flows/kosli": GET http://localhost/api/v2/flows/kosli giving up after 4 …
```
=> always silence retryable client logging

cmd/kosli/attestJira.go, cmd/kosli/reportEvidenceCommitJira.go, cmd/kosli/reportEvidenceCommitJira_test.go, cmd/kosli/root.go, internal/gitview/gitView.go, internal/gitview/gitView_test.go
- **Added jira-secondary-source argument to jira attest command**
- **Added test of duplicate keys found**
- **Updated order in test result**
- **Sort jira issues**
=> Added option to include a secondary source for jira issue attestation

docs.kosli.com/content/faq/_index.md, docs.kosli.com/content/getting_started/approvals.md, docs.kosli.com/content/getting_started/artifacts.md, docs.kosli.com/content/getting_started/attestations.md, docs.kosli.com/content/getting_started/environments.md, docs.kosli.com/content/getting_started/flows.md, docs.kosli.com/content/getting_started/install.md, docs.kosli.com/content/getting_started/next.md, docs.kosli.com/content/getting_started/policies.md, docs.kosli.com/content/getting_started/trails.md, docs.kosli.com/content/template_ref/_index.md, docs.kosli.com/content/understand_kosli/concepts.md
- add a section in getting started
- add env policy to the concepts section
- update CLI commands to make them copyable and remove leading `$`
- mention custom attestation types in flow template ref (fixes #416 )
relates to kosli-dev/server#1943
=> add env policy section to docs

cmd/kosli/attestCustom.go, cmd/kosli/attestation.go, cmd/kosli/root.go, cmd/kosli/snapshotPath.go, cmd/kosli/snapshotPaths.go, cmd/kosli/testdata/output/docs/snyk.md
- Fixes incorrect flag name in attest-custom examples.
- Adds  sentence for --attestation-data to attest-custom Synopsis
- Move commit/redaction text out of binding text (to match other attest commands)
- Minor layout/text tweaks
=> cli reference text fixing and tidying

cmd/kosli/docs.go, cmd/kosli/docs_test.go, cmd/kosli/testdata/output/docs/snyk.md
Billy created a document for Emburse using chat gpt. It looks like AI is being influenced by the examples at the end of each CLI command at https://docs.kosli.com/
This commit:
- removes flags that would commonly be set via environment-variables. Specifically, --api-token, --host, --org, --flow, --trail.
- adds some text explaining the assumption that these are set via env-vars in the examples.
- removes the trailing backslashes.
Note: It does this in the docs processing of the source .go files. In other words, the flags still exist in the original source in case we wish to undo this change.
=> Don't show api-token,host,org,flow,trail in example use cases

docs.kosli.com/content/getting_started/policies.md
=> Fix typo in policies

.github/workflows/test.yml, Makefile, bin/reset-or-start-server.sh, docker-compose.yml, hack/get-server-image.sh
related to kosli-dev/server#3151
=> get latest running server image from staging for tests

charts/k8s-reporter/README.md, docs.kosli.com/content/helm/_index.md
=> Update helm docs

docs.kosli.com/content/getting_started/environments.md
Updated the documentation to match the CLI command in https://docs.kosli.com/client_reference/kosli_create_environment/
=> Fix CLI command syntax for creating an environment in documentation

cmd/kosli/attestSonar_test.go, cmd/kosli/testdata/sonar/sonarcloud/.scannerwork-old/report-task.txt, internal/sonar/sonar.go
Just a quick adjustment to get tests passing again since SonarQube seem to have deleted some data being used in one of the test cases.
I'll go through a do a full update of tests later.
=> Add extra not-found error check for analyses deleted by SonarQube

.github/workflows/release.yml
The runner used in the packaging steps needed to be upgraded to the latest version, to keep current with the runners available within Github actions.
=> Upgrade ubuntu version for package steps
